dist: focal
sudo: false
language: ruby
rvm:
- '2.7'
deploy:
  provider: rubygems
  api_key:
    secure: B3uPGgxPtGExfpjUPiYGwtEndXHJUGH3/ft1/Qu8AGioUTb34rdpH2woo3xAEcBSWwbGfqmelpYmmkL3xqfkL0JgeiE4tXJ2J3pX+z8MTQRPXdsdYZvd8bv4TA229tb6prfALhyKEmCXAvUPu9BGB/nB6Peni663vZQhF9K3r1V/M6Z6WPHgQVUPse5Mjoe+uLzHhtEf8EYEwRD2GGBBxPbhLIoIZfbCvwYNTKkPRh9ReMI0LUmOiznVxpyjALXbY5TNME7CyyIrDW/coglh2G4rBMCzmpGS9YLwDevxrobU/H5GXmnDftFaAdn3So/nnnVpnxV4rZKHz/tXSoAq40ZHOvCWfXiUGvCSGWHeW/XI2ozzmZlifrryzbKJbs4MM7+ngwx5OiumeNLJdjkgAz+aPHzhXImJDZZOFff5YiJ+xy2tB0HeBlXMhq4vNt7VTbH/TbyBc+1Y+ufVl+mKkVZiuAU5bRbo/S9dI/fQwJeJLnCr3E0ZsJO9efwQZ+nus7mi7c7ZaTMEZyM7lVbRGegSHzy9UM6ipAd/KFjLOe81MZ4UTU6Sut0m3vcjK57feyDVTOHNsQinlvi6TpCYZFhW4NsRpZlfoRg/f1fku8BX1YFw7/1YGqtP+SXcUknD3Ot8IuC3++Y1S9yBj6vFDJ0fyG5ow+JP7DXaSTuf0SI=
  gem: github_merge_sign
  on:
    tags: true
    ruby: '2.7'
